-- Fase 1 di "gestione portfolio": crea la tabella per i metadati delle immagini
-- del portfolio e migra i metadati (non i file, che restano in public/images/)
-- delle 126 immagini già esistenti. Vedi
-- docs/superpowers/specs/2026-07-17-portfolio-fase1-design.md.
--
-- COME ATTIVARLO: Aprire il progetto su https://supabase.com -> SQL Editor,
-- incollare ed eseguire questo intero file.

create table portfolio_immagini (
  id bigint generated by default as identity primary key,
  src text not null,
  titolo text not null,
  categoria text not null,
  ordine integer not null default 0,
  pubblicato boolean not null default true
);

alter table portfolio_immagini enable row level security;

create policy "portfolio_immagini_select_pubblico"
  on portfolio_immagini for select
  to anon, authenticated
  using (true);

-- Composizioni (19 immagini)
insert into portfolio_immagini (src, titolo, categoria, ordine) values
  ('images/composizioni/tigre e fiori.webp', 'Tigre e Fiori', 'Composizioni', 0),
  ('images/composizioni/autumn killed.webp', 'Autumn Killed', 'Composizioni', 1),
  ('images/composizioni/lovebirds.webp', 'Lovebirds', 'Composizioni', 2),
  ('images/composizioni/primavera.webp', 'Primavera', 'Composizioni', 3),
  ('images/composizioni/Aprile.webp', 'Aprile', 'Composizioni', 4),
  ('images/composizioni/coniglio.webp', 'Coniglio', 'Composizioni', 5),
  ('images/composizioni/topo.webp', 'Topo', 'Composizioni', 6),
  ('images/composizioni/testamorto.webp', 'Testamorto', 'Composizioni', 7),
  ('images/composizioni/barbagianni1.webp', 'Barbagianni 1', 'Composizioni', 8),
  ('images/composizioni/maggio.webp', 'Maggio', 'Composizioni', 9),
  ('images/composizioni/barbagianni.webp', 'Barbagianni', 'Composizioni', 10),
  ('images/composizioni/giugno.webp', 'Giugno', 'Composizioni', 11),
  ('images/composizioni/barbagianni e luna.webp', 'Barbagianni e Luna', 'Composizioni', 12),
  ('images/composizioni/volpe_piante.webp', 'Volpe Piante', 'Composizioni', 13),
  ('images/composizioni/volpe autunnale.webp', 'Volpe Autunnale', 'Composizioni', 14),
  ('images/composizioni/corvo e ciliegie.webp', 'Corvo e Ciliegie', 'Composizioni', 15),
  ('images/composizioni/farfalla e gigli.webp', 'Farfalla e Gigli', 'Composizioni', 16),
  ('images/composizioni/cfarfalla e gigli comp.webp', 'Cfarfalla e Gigli Comp', 'Composizioni', 17),
  ('images/composizioni/balene e alghe.webp', 'Balene e Alghe', 'Composizioni', 18);

-- Animali (26 immagini)
insert into portfolio_immagini (src, titolo, categoria, ordine) values
  ('images/animali/balene.webp', 'Balene', 'Animali', 0),
  ('images/animali/tucan.webp', 'Tucan', 'Animali', 1),
  ('images/animali/tartaruga.webp', 'Tartaruga', 'Animali', 2),
  ('images/animali/maialino.webp', 'Maialino', 'Animali', 3),
  ('images/animali/granchio.webp', 'Granchio', 'Animali', 4),
  ('images/animali/bird1.webp', 'Bird 1', 'Animali', 5),
  ('images/animali/bird2.webp', 'Bird 2', 'Animali', 6),
  ('images/animali/bird3.webp', 'Bird 3', 'Animali', 7),
  ('images/animali/kingfisher.webp', 'Kingfisher', 'Animali', 8),
  ('images/animali/aragiacinto.webp', 'Aragiacinto', 'Animali', 9),
  ('images/animali/manta.webp', 'Manta', 'Animali', 10),
  ('images/animali/polipo.webp', 'Polipo', 'Animali', 11),
  ('images/animali/rana.webp', 'Rana', 'Animali', 12),
  ('images/animali/coniglio1.webp', 'Coniglio 1', 'Animali', 13),
  ('images/animali/coniglio2.webp', 'Coniglio 2', 'Animali', 14),
  ('images/animali/cerbiatto1.webp', 'Cerbiatto 1', 'Animali', 15),
  ('images/animali/topo.webp', 'Topo', 'Animali', 16),
  ('images/animali/coniglio3.webp', 'Coniglio 3', 'Animali', 17),
  ('images/animali/papera.webp', 'Papera', 'Animali', 18),
  ('images/animali/cerbiatto2.webp', 'Cerbiatto 2', 'Animali', 19),
  ('images/animali/granchio PICCOLA.webp', 'Granchio Piccola', 'Animali', 20),
  ('images/animali/polipo PICCOLA.webp', 'Polipo Piccola', 'Animali', 21),
  ('images/animali/barbagianni senza luna.webp', 'Barbagianni senza Luna', 'Animali', 22),
  ('images/animali/barbagianni.webp', 'Barbagianni', 'Animali', 23),
  ('images/animali/volpe1.webp', 'Volpe 1', 'Animali', 24),
  ('images/animali/volpe2.webp', 'Volpe 2', 'Animali', 25);

-- Insetti (16 immagini)
insert into portfolio_immagini (src, titolo, categoria, ordine) values
  ('images/insetti/ape1.webp', 'Ape 1', 'Insetti', 0),
  ('images/insetti/ape2.webp', 'Ape 2', 'Insetti', 1),
  ('images/insetti/farfalla verde1.webp', 'Farfalla Verde 1', 'Insetti', 2),
  ('images/insetti/falena verde.webp', 'Falena Verde', 'Insetti', 3),
  ('images/insetti/farfalla verde2.webp', 'Farfalla Verde 2', 'Insetti', 4),
  ('images/insetti/deadhead moth.webp', 'Deadhead Moth', 'Insetti', 5),
  ('images/insetti/farfalla marrone e gialla.webp', 'Farfalla Marrone e Gialla', 'Insetti', 6),
  ('images/insetti/farfalla gialla.webp', 'Farfalla Gialla', 'Insetti', 7),
  ('images/insetti/farfalla marrone.webp', 'Farfalla Marrone', 'Insetti', 8),
  ('images/insetti/ape3.webp', 'Ape 3', 'Insetti', 9),
  ('images/insetti/coccinella.webp', 'Coccinella', 'Insetti', 10),
  ('images/insetti/coccinella1.webp', 'Coccinella 1', 'Insetti', 11),
  ('images/insetti/farfalle colorate/farfalla colorata1.webp', 'Farfalla Colorata 1', 'Insetti', 12),
  ('images/insetti/farfalle colorate/farfalla colorata2.webp', 'Farfalla Colorata 2', 'Insetti', 13),
  ('images/insetti/farfalle colorate/farfalla colorata3.webp', 'Farfalla Colorata 3', 'Insetti', 14),
  ('images/insetti/farfalle colorate/farfalla colorata4.webp', 'Farfalla Colorata 4', 'Insetti', 15);

-- Elementi Botanici (65 immagini)
insert into portfolio_immagini (src, titolo, categoria, ordine) values
  ('images/elementi botanici/tulip.webp', 'Tulip', 'Elementi Botanici', 0),
  ('images/elementi botanici/fiore.webp', 'Fiore', 'Elementi Botanici', 1),
  ('images/elementi botanici/monstera.webp', 'Monstera', 'Elementi Botanici', 2),
  ('images/elementi botanici/foglia1.webp', 'Foglia 1', 'Elementi Botanici', 3),
  ('images/elementi botanici/foglia2.webp', 'Foglia 2', 'Elementi Botanici', 4),
  ('images/elementi botanici/Melagrana1.webp', 'Melagrana 1', 'Elementi Botanici', 5),
  ('images/elementi botanici/Melagrana2.webp', 'Melagrana 2', 'Elementi Botanici', 6),
  ('images/elementi botanici/bacche1.webp', 'Bacche 1', 'Elementi Botanici', 7),
  ('images/elementi botanici/bacche2.webp', 'Bacche 2', 'Elementi Botanici', 8),
  ('images/elementi botanici/melagranaa1.webp', 'Melagranaa 1', 'Elementi Botanici', 9),
  ('images/elementi botanici/melagranaa2.webp', 'Melagranaa 2', 'Elementi Botanici', 10),
  ('images/elementi botanici/Fungo1.webp', 'Fungo 1', 'Elementi Botanici', 11),
  ('images/elementi botanici/Fungo2.webp', 'Fungo 2', 'Elementi Botanici', 12),
  ('images/elementi botanici/viole.webp', 'Viole', 'Elementi Botanici', 13),
  ('images/elementi botanici/viola2.webp', 'Viola 2', 'Elementi Botanici', 14),
  ('images/elementi botanici/ciliegio1.webp', 'Ciliegio 1', 'Elementi Botanici', 15),
  ('images/elementi botanici/ciliegio2.webp', 'Ciliegio 2', 'Elementi Botanici', 16),
  ('images/elementi botanici/fiore bianco 1.webp', 'Fiore Bianco 1', 'Elementi Botanici', 17),
  ('images/elementi botanici/fiore bianco 2.webp', 'Fiore Bianco 2', 'Elementi Botanici', 18),
  ('images/elementi botanici/Fungo3.webp', 'Fungo 3', 'Elementi Botanici', 19),
  ('images/elementi botanici/green1.webp', 'Green 1', 'Elementi Botanici', 20),
  ('images/elementi botanici/uovo.webp', 'Uovo', 'Elementi Botanici', 21),
  ('images/elementi botanici/rosa.webp', 'Rosa', 'Elementi Botanici', 22),
  ('images/elementi botanici/fiore giallo.webp', 'Fiore Giallo', 'Elementi Botanici', 23),
  ('images/elementi botanici/green2.webp', 'Green 2', 'Elementi Botanici', 24),
  ('images/elementi botanici/green3.webp', 'Green 3', 'Elementi Botanici', 25),
  ('images/elementi botanici/green4.webp', 'Green 4', 'Elementi Botanici', 26),
  ('images/elementi botanici/green5.webp', 'Green 5', 'Elementi Botanici', 27),
  ('images/elementi botanici/green6.webp', 'Green 6', 'Elementi Botanici', 28),
  ('images/elementi botanici/green7.webp', 'Green 7', 'Elementi Botanici', 29),
  ('images/elementi botanici/green9.webp', 'Green 9', 'Elementi Botanici', 30),
  ('images/elementi botanici/green10.webp', 'Green 10', 'Elementi Botanici', 31),
  ('images/elementi botanici/Green 7 digital.webp', 'Green 7 Digital', 'Elementi Botanici', 32),
  ('images/elementi botanici/giglio1.webp', 'Giglio 1', 'Elementi Botanici', 33),
  ('images/elementi botanici/giglio2.webp', 'Giglio 2', 'Elementi Botanici', 34),
  ('images/elementi botanici/foglie giglio.webp', 'Foglie Giglio', 'Elementi Botanici', 35),
  ('images/elementi botanici/lavanda1.webp', 'Lavanda 1', 'Elementi Botanici', 36),
  ('images/elementi botanici/lavanda2.webp', 'Lavanda 2', 'Elementi Botanici', 37),
  ('images/elementi botanici/pesche.webp', 'Pesche', 'Elementi Botanici', 38),
  ('images/elementi botanici/fiore logo 1.webp', 'Fiore Logo 1', 'Elementi Botanici', 39),
  ('images/elementi botanici/fiore logo 2.webp', 'Fiore Logo 2', 'Elementi Botanici', 40),
  ('images/elementi botanici/pere/pere1.webp', 'Pere 1', 'Elementi Botanici', 41),
  ('images/elementi botanici/pere/pere2.webp', 'Pere 2', 'Elementi Botanici', 42),
  ('images/elementi botanici/pere/pere3.webp', 'Pere 3', 'Elementi Botanici', 43),
  ('images/elementi botanici/pere/pere4.webp', 'Pere 4', 'Elementi Botanici', 44),
  ('images/elementi botanici/pere/pere5.webp', 'Pere 5', 'Elementi Botanici', 45),
  ('images/elementi botanici/pere/pattern pere.webp', 'Pattern Pere', 'Elementi Botanici', 46),
  ('images/elementi botanici/fragole/fragole1.webp', 'Fragole 1', 'Elementi Botanici', 47),
  ('images/elementi botanici/fragole/fragole2.webp', 'Fragole 2', 'Elementi Botanici', 48),
  ('images/elementi botanici/fragole/fragole3.webp', 'Fragole 3', 'Elementi Botanici', 49),
  ('images/elementi botanici/fragole/fragole4.webp', 'Fragole 4', 'Elementi Botanici', 50),
  ('images/elementi botanici/fragole/fragole5.webp', 'Fragole 5', 'Elementi Botanici', 51),
  ('images/elementi botanici/fragole/fragole6.webp', 'Fragole 6', 'Elementi Botanici', 52),
  ('images/elementi botanici/fragole/fragole7.webp', 'Fragole 7', 'Elementi Botanici', 53),
  ('images/elementi botanici/fragole/fragole8.webp', 'Fragole 8', 'Elementi Botanici', 54),
  ('images/elementi botanici/fragole/fragole9.webp', 'Fragole 9', 'Elementi Botanici', 55),
  ('images/elementi botanici/fragole/fragole10.webp', 'Fragole 10', 'Elementi Botanici', 56),
  ('images/elementi botanici/fragole/fragole11.webp', 'Fragole 11', 'Elementi Botanici', 57),
  ('images/elementi botanici/fragole/curva fragole.webp', 'Curva Fragole', 'Elementi Botanici', 58),
  ('images/elementi botanici/limoni/limoni1.webp', 'Limoni 1', 'Elementi Botanici', 59),
  ('images/elementi botanici/limoni/limoni2.webp', 'Limoni 2', 'Elementi Botanici', 60),
  ('images/elementi botanici/limoni/limoni3.webp', 'Limoni 3', 'Elementi Botanici', 61),
  ('images/elementi botanici/limoni/limoni4.webp', 'Limoni 4', 'Elementi Botanici', 62),
  ('images/elementi botanici/limoni/limoni5.webp', 'Limoni 5', 'Elementi Botanici', 63),
  ('images/elementi botanici/limoni/limoni6.webp', 'Limoni 6', 'Elementi Botanici', 64);
